### ISSUE TITLE
compatibility problem with the trac 0.12

### ISSUE THREAD

**Issue by proydakov** [trac-hacks/TicketMoverPlugin#1]
Hello

Successfully used the plugin with trac 0.10. Recently spent updating and pragin stopped working - it is no longer displayed on the right of tickets. Depending TicketSidebarProviderPlugin and TracSqlHelperScript installed and working. The installation of the plugin was producing a Web Admin.
In what may be the problem? Or, if the performance of trac 0.12 is not possible, can you advise analogue.

Thank you.

**Comment by UnwashedMeme** [comment]
We're running it on trac 0.12 just fine; i think the expectations might be a bit off. When i updated it to work for 0.12 for us, I changed it somewhat and didn't worry about keeping 0.11 in sync.

The right sidebar is no longer part of this version, it now shows up under "Action" down at the bottom where you control the state of the ticket. TicketSidebarProviderPlgin should no longer be required, not sure if it is.   That action won't show up unless you have "TICKET_ADMIN" privilege and the plugin is aware of other tracs to move to.

The list of tracs to move it to is generated based on sibling directories of the current ticket's trac. This isn't currently configurable-- pulling that from autointertrac or making it configurable might be nice but this works for our use case.

I also just did a push from our local clone up to github that has some updates and bugfixes; pull that and give it a try-- I'm going to close this issue as not valid; but feel free to open new ones with any bugs you encounter from there.
