### ISSUE TITLE
Any interest in adding your plugin to the trac-hacks organization?

### ISSUE THREAD

**Issue by rjollos** [trac-hacks/TicketMoverPlugin#4]
Hi,

I'm an administrator for trac-hacks.org.  We've created an organization on GitHub and are inviting authors of trac-hacks plugins to join the organization.  Your repository could be transferred into the organization as described in the [GitHub docs](https://help.github.com/articles/transferring-a-repository/).  You'd retain full control over the repository, but the hope is that it will be easier for users on GitHub to find trac-hacks plugins, such as yours, by viewing the trac-hacks organization. We also plan to eventually add search capabilities that aggregate the plugins available on trac-hacks.org and github.com/trac-hacks, to provide a single index of all plugins available for Trac.

In the future, if you choose to no longer maintain the plugin, the organization would be able to provide commit access to new developers.  This would only be done with your permission, as has been the policy for plugins hosted on trac-hacks.org.  If you've already decided to no longer maintain the plugin, we would particularly appreciate you transferring the plugin to the trac-hacks organization so that we can help find new maintainers for it.

Thank you for your consideration.

Kind regards,
Ryan

(Apologies if I open a ticket against two of your plugins. I'm doing a manual search of GitHub to find Trac plugins and invite plugin authors; it's sometimes difficult to keep everything straight).

**Comment by UnwashedMeme** [comment]
Sorry I didn't respond for so long. I've not really been maintaining this (but there hasn't been much maintenance to do).

If you're still interested in having this under trac-hacks and want to add more people as committers that's fine by me.

**Comment by rjollos** [comment]
Thanks! You should receive an invite to join the trac-hacks organization. You'll have general Admin access to the trac-hacks organization which will allow you to execute [these steps](https://help.github.com/articles/about-repository-transfers) and transfer the repository. You'll be owner of the TicketMoverPlugin project in the @trac-hacks organization.

**Comment by UnwashedMeme** [comment]
@bobbysmith007 I've moved this repo into trac-hacks org; you might want to join the @trac-hacks/ticketmoverplugin team, and update the requirements file for our trac server.

**Comment by rjollos** [comment]
Looks good. I added @bobbysmith007 to the team. Thanks!
